 const mills=[{
    id:1,
        name:"Alcock's Mill",
        place:"Forthampton",
        year: "1845",
        type:"Tower",
    },
    {
    id:2,
    name:"Splash Mill",
    place:"Wraysbury",
    year: "1996",
    type:"Smock",
    },
    {id:3,
    name:"The Kendalls",
    place:"Gillingham",
    year: "1895",
    type:"Titt iron wind engine",
    },
    {id:4,
        name:"Windmill Hill Mill",
        place:"Gateshead",
        year: "1898",
        type:"Post",
    },
    {id:5,
        name:"Borough Mill",
        place:"Gateshead",
        year: "1837",
        type:"Tower",
    },
    {id:6,
        name:"Whickham Mill",
        place:"Whickham",
        year: "1720",
        type:"Tower",
    },
    {id:7,
        name:"Cam Mills",
        place:"Dursley",
        year: "1901",
        type:"Titt iron wind engine",
    },
    {id:8,
        name:"Haigh Mill",
        place:"Haigh",
        year: "1845",
        type:"Tower",
    },
    {id:9,
        name:"Forest's Mill",
        place:"Lydiate",
        year: "1768",
        type:"Tower",
    },
    {id:10,
        name:"Chimney Mill",
        place:"Newcastle",
        year: "1793",
        type:"Smock",
    }
    ];
 export default mills;
